### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by LordSuperior77** [PlaybackDevs/Superior-Reign#1]
We have to make a page for the game to be on. The page will contain:

- The box where the game will be 

- Contributors logos

- Title

**Comment by createjump** [comment]
I've enabled github pages on my fork, i should be sending a PR any time soon after I get source cleaned up slightly and add some hello world in Java code (in all honesty I don't get Java) so that there is at least something

**Comment by createjump** [comment]
IMHO having a JVM (java) app would be WAY less anemic, and would make the game faster, which DOES matter. ( It would have a wider target demographic.)

**Comment by createjump** [comment]
Closing- old and irrleavent to the C# decision made quite a while ago.
